@startuml

skinparam roundcorner 15
skinparam componentStyle rectangle

<style>
process {
    BackgroundColor #C5DFEE
}
</style>

package "Input" {
    component "Gdx.input" as GdxInput
}

package Movement {
    package Input as Movement.Input {
        process ControllerMovementInputSystem
        process MultiplexMovementInputSystem
        process AIMovementInputSystem
        component MovementInput.AI
        component MovementInput.Controller
        component MovementInput.Multiplex
    }

    package FaceDirection as Movement.FaceDirection {
        component FaceDirection
        process FaceDirectionSystem
    }

    package Velocity as Movement.Velocity {
        component Velocity
        process VelocitySystem
    }

    package Position as Movement.Position{
        component Position
        process PositionChangeSystem
    }

    component Speed

    package Animation as Movement.Animation {
        process MovementAnimationSystem
    }
}

package Animation {
    component CurrentAnimation
    process SpriteAnimationSystem
}

package Sprite {
    component CurrentSprite
    process CurrentSpritePositionSystem
    process SpriteRenderingSystem
}

GdxInput --> ControllerMovementInputSystem

ControllerMovementInputSystem --> MovementInput.Controller

MovementInput.Controller --> MultiplexMovementInputSystem

AIMovementInputSystem --> MovementInput.AI
MovementInput.AI --> MultiplexMovementInputSystem

MultiplexMovementInputSystem --> MovementInput.Multiplex

MovementInput.Multiplex --> FaceDirectionSystem
FaceDirectionSystem --> FaceDirection

FaceDirection --> MovementAnimationSystem
Velocity --> MovementAnimationSystem
MovementAnimationSystem --> CurrentAnimation

MovementInput.Multiplex --> VelocitySystem

VelocitySystem --> Velocity

Velocity --> PositionChangeSystem
Speed --> VelocitySystem

PositionChangeSystem --> Position

Position --> CurrentSpritePositionSystem
CurrentSpritePositionSystem --> CurrentSprite: setOriginBasedPosition

CurrentSprite --> SpriteRenderingSystem

CurrentAnimation --> SpriteAnimationSystem

SpriteAnimationSystem --> CurrentSprite

@enduml
